[php]
error_reporting = E_ALL
; error_reporting = E_ALL ^ E_DEPRECATED
short_open_tag = On
display_errors = On
display_startup_errors = On
error_log = "/var/log/php/error.log"
log_errors = On
cgi.fix_pathinfo = 0
date.timezone = "Europe/Moscow"
mbstring.func_overload = 0
mbstring.internal_encoding = "UTF-8"
max_input_vars = 10000
post_max_size = 1024M
memory_limit = 256M
upload_max_filesize = 1024M
output_buffering = 4096
zlib.output_compression = On
expose_php = Off
max_execution_time = 30
session.gc_probability = 0

[opcache]
opcache.enable = 1
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.max_accelerated_files = 100000
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 64
opcache.fast_shutdown = 1
opcache.error_log = "/var/log/php/opcache.log"
opcache.optimization_level = 0xFFFFFFFF
opcache.enable_cli = 0
opcache.max_wasted_percentage = 5
opcache.consistency_checks = 0
opcache.huge_code_pages = 1
realpath_cache_size = 512k
realpath_cache_ttl = 600

[xdebug]
xdebug.mode = develop,debug
xdebug.start_with_request = trigger
xdebug.discover_client_host = false
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.log = "/var/log/php/xdebug-error.log"
