[www]
; Важно: добавь только нужные параметры, чтобы не перезаписывать всё остальное

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 1000

slowlog = /var/log/php/fpm-slow.log
request_slowlog_timeout = 5s
request_terminate_timeout = 1800s
