compress
dateext
missingok
notifempty

/var/log/nginx/*.log*
/var/log/php/*.log*
/var/log/php/cachegrind.out.*
/var/log/mysql/*.log*
/var/log/memcached/*.log* {
    hourly
    rotate 10
    maxsize 50M
    maxage 1
    copytruncate
    delaycompress
    missingok
    notifempty
}
