compress
dateext
missingok
notifempty

/var/log/nginx/*.log /var/log/php/*.log /var/log/mysql/*.log /var/log/memcached/*.log {
    hourly
    rotate 48
    maxsize 50M
    copytruncate
    delaycompress
    missingok
    notifempty
}